// Generated by CoffeeScript 2.0.0-beta3
var Button;

import {
  Observable
} from './Observable';

import PropTypes from 'prop-types';

Button = class Button extends Observable {
  constructor(props) {
    super(props);
  }

  onClick() {
    return this.props.onClick();
  }

  brew(v) {
    super.brew(v);
    return v.button({
      onClick: this.onClick.bind(this)
    }, this.props.label);
  }

};

Button.propTypes = {
  onClick: PropTypes.func.isRequired,
  label: PropTypes.string.isRequired
};

export default Button;
