// Generated by CoffeeScript 2.0.0-beta3
var element;

import React from 'react';

import {
  render
} from 'react-dom';

import {
  AppContainer
} from 'react-hot-loader';

import Todo from './Todo';

import {
  get
} from 'lodash';

import Calendar from './Calendar';

import reactKup from 'react-kup';

element = function() {
  return reactKup(function(k) {
    return k.build(AppContainer, function() {
      return k.div(function() {
        k.build(Calendar, {
          date: new Date
        });
        return k.build(Todo, {
          name: 'Home'
        });
      });
    });
  });
};

render(element(), document.getElementById('root'));
